import type { CatalogEntry } from "./types";

/**
 * db.kasb.or.kr "회계기준" 전체 카탈로그 (2026-08-25 기준, 사이트 좌측 메뉴 전수 확인).
 * ESG/지속가능성 공시기준(별도 사이트 섹션, /esg)은 범위 밖이라 제외.
 */
export const CATALOG: CatalogEntry[] = [
  // ---- K-IFRS 본기준서 ----
  { stdNum: 1001, category: "K-IFRS", title: "재무제표 표시" },
  { stdNum: 1002, category: "K-IFRS", title: "재고자산" },
  { stdNum: 1007, category: "K-IFRS", title: "현금흐름표" },
  { stdNum: 1008, category: "K-IFRS", title: "회계정책, 회계추정치 변경과 오류" },
  { stdNum: 1010, category: "K-IFRS", title: "보고기간후사건" },
  { stdNum: 1012, category: "K-IFRS", title: "법인세" },
  { stdNum: 1016, category: "K-IFRS", title: "유형자산" },
  { stdNum: 1019, category: "K-IFRS", title: "종업원급여" },
  { stdNum: 1020, category: "K-IFRS", title: "정부보조금의 회계처리와 정부지원의 공시" },
  { stdNum: 1021, category: "K-IFRS", title: "환율변동효과" },
  { stdNum: 1023, category: "K-IFRS", title: "차입원가" },
  { stdNum: 1024, category: "K-IFRS", title: "특수관계자 공시" },
  { stdNum: 1026, category: "K-IFRS", title: "퇴직급여제도에 의한 회계처리와 보고" },
  { stdNum: 1027, category: "K-IFRS", title: "별도재무제표" },
  { stdNum: 1028, category: "K-IFRS", title: "관계기업과 공동기업에 대한 투자" },
  { stdNum: 1029, category: "K-IFRS", title: "초인플레이션 경제에서의 재무보고" },
  { stdNum: 1032, category: "K-IFRS", title: "금융상품: 표시" },
  { stdNum: 1033, category: "K-IFRS", title: "주당이익" },
  { stdNum: 1034, category: "K-IFRS", title: "중간재무보고" },
  { stdNum: 1036, category: "K-IFRS", title: "자산손상" },
  { stdNum: 1037, category: "K-IFRS", title: "충당부채, 우발부채, 우발자산" },
  { stdNum: 1038, category: "K-IFRS", title: "무형자산" },
  { stdNum: 1039, category: "K-IFRS", title: "금융상품: 인식과 측정" },
  { stdNum: 1040, category: "K-IFRS", title: "투자부동산" },
  { stdNum: 1041, category: "K-IFRS", title: "농림어업" },
  { stdNum: 1101, category: "K-IFRS", title: "한국채택국제회계기준의 최초채택" },
  { stdNum: 1102, category: "K-IFRS", title: "주식기준보상" },
  { stdNum: 1103, category: "K-IFRS", title: "사업결합" },
  { stdNum: 1105, category: "K-IFRS", title: "매각예정비유동자산과 중단영업" },
  { stdNum: 1106, category: "K-IFRS", title: "광물자원의 탐사와 평가" },
  { stdNum: 1107, category: "K-IFRS", title: "금융상품: 공시" },
  { stdNum: 1108, category: "K-IFRS", title: "영업부문" },
  { stdNum: 1109, category: "K-IFRS", title: "금융상품" },
  { stdNum: 1110, category: "K-IFRS", title: "연결재무제표" },
  { stdNum: 1111, category: "K-IFRS", title: "공동약정" },
  { stdNum: 1112, category: "K-IFRS", title: "타 기업에 대한 지분의 공시" },
  { stdNum: 1113, category: "K-IFRS", title: "공정가치 측정" },
  { stdNum: 1114, category: "K-IFRS", title: "규제이연계정" },
  { stdNum: 1115, category: "K-IFRS", title: "고객과의 계약에서 생기는 수익" },
  { stdNum: 1116, category: "K-IFRS", title: "리스" },
  { stdNum: 1117, category: "K-IFRS", title: "보험계약" },
  { stdNum: 1118, category: "K-IFRS", title: "재무제표 표시와 공시(조기적용가능)" },
  // ---- K-IFRS 해석서 ----
  { stdNum: 2010, category: "K-IFRS 해석서", title: "정부지원: 영업활동과 특정한 관련이 없는 경우" },
  { stdNum: 2025, category: "K-IFRS 해석서", title: "법인세: 기업이나 주주의 납세지위 변동" },
  { stdNum: 2029, category: "K-IFRS 해석서", title: "민간투자사업: 공시" },
  { stdNum: 2032, category: "K-IFRS 해석서", title: "무형자산: 웹 사이트 원가" },
  { stdNum: 2101, category: "K-IFRS 해석서", title: "사후처리 및 복구관련 충당부채의 변경" },
  { stdNum: 2102, category: "K-IFRS 해석서", title: "조합원 지분과 유사 지분" },
  { stdNum: 2105, category: "K-IFRS 해석서", title: "사후처리, 복구 및 환경정화를 위한 기금의 지분에 대한 권리" },
  { stdNum: 2106, category: "K-IFRS 해석서", title: "특정 시장에 참여함에 따라 발생하는 부채: 폐전기·전자제품" },
  { stdNum: 2107, category: "K-IFRS 해석서", title: "기업회계기준서 제1029호 '초인플레이션 경제에서의 재무보고'에 따른 재작성 방법의 적용" },
  { stdNum: 2110, category: "K-IFRS 해석서", title: "중간재무보고와 손상" },
  { stdNum: 2112, category: "K-IFRS 해석서", title: "민간투자사업" },
  { stdNum: 2114, category: "K-IFRS 해석서", title: "기업회계기준서 제1019호: 확정급여자산한도, 최소적립요건 및 그 상호작용" },
  { stdNum: 2116, category: "K-IFRS 해석서", title: "해외사업장순투자의 위험회피" },
  { stdNum: 2117, category: "K-IFRS 해석서", title: "소유주에 대한 비현금자산의 분배" },
  { stdNum: 2119, category: "K-IFRS 해석서", title: "지분상품에 의한 금융부채의 소멸" },
  { stdNum: 2120, category: "K-IFRS 해석서", title: "노천광산 생산단계의 박토원가" },
  { stdNum: 2121, category: "K-IFRS 해석서", title: "부담금" },
  { stdNum: 2122, category: "K-IFRS 해석서", title: "외화 거래와 선지급·선수취 대가" },
  { stdNum: 2123, category: "K-IFRS 해석서", title: "법인세 처리의 불확실성" },
  // ---- 일반기업회계기준 (장 번호) ----
  { stdNum: 1, category: "일반기업회계기준", title: "목적, 구성 및 적용" },
  { stdNum: 2, category: "일반기업회계기준", title: "재무제표의 작성과 표시Ⅰ" },
  { stdNum: 3, category: "일반기업회계기준", title: "재무제표의 작성과 표시Ⅱ" },
  { stdNum: 4, category: "일반기업회계기준", title: "연결재무제표" },
  { stdNum: 5, category: "일반기업회계기준", title: "회계정책, 회계추정의 변경 및 오류" },
  { stdNum: 6, category: "일반기업회계기준", title: "금융자산·금융부채" },
  { stdNum: 7, category: "일반기업회계기준", title: "재고자산" },
  { stdNum: 8, category: "일반기업회계기준", title: "지분법" },
  { stdNum: 9, category: "일반기업회계기준", title: "조인트벤처 투자" },
  { stdNum: 10, category: "일반기업회계기준", title: "유형자산" },
  { stdNum: 11, category: "일반기업회계기준", title: "무형자산" },
  { stdNum: 12, category: "일반기업회계기준", title: "사업결합" },
  { stdNum: 13, category: "일반기업회계기준", title: "리스" },
  { stdNum: 14, category: "일반기업회계기준", title: "충당부채, 우발부채 및 우발자산" },
  { stdNum: 15, category: "일반기업회계기준", title: "자본" },
  { stdNum: 16, category: "일반기업회계기준", title: "수익" },
  { stdNum: 17, category: "일반기업회계기준", title: "정부보조금의 회계처리" },
  { stdNum: 18, category: "일반기업회계기준", title: "차입원가자본화" },
  { stdNum: 19, category: "일반기업회계기준", title: "주식기준보상" },
  { stdNum: 20, category: "일반기업회계기준", title: "자산손상" },
  { stdNum: 21, category: "일반기업회계기준", title: "종업원급여" },
  { stdNum: 22, category: "일반기업회계기준", title: "법인세회계" },
  { stdNum: 23, category: "일반기업회계기준", title: "환율변동효과" },
  { stdNum: 24, category: "일반기업회계기준", title: "보고기간후사건" },
  { stdNum: 25, category: "일반기업회계기준", title: "특수관계자 공시" },
  { stdNum: 26, category: "일반기업회계기준", title: "기본주당이익" },
  { stdNum: 27, category: "일반기업회계기준", title: "특수활동" },
  { stdNum: 28, category: "일반기업회계기준", title: "중단사업" },
  { stdNum: 29, category: "일반기업회계기준", title: "중간재무제표" },
  { stdNum: 30, category: "일반기업회계기준", title: "일반기업회계기준의 최초채택" },
  { stdNum: 31, category: "일반기업회계기준", title: "중소기업 회계처리 특례" },
  { stdNum: 32, category: "일반기업회계기준", title: "동일지배거래" },
  { stdNum: 33, category: "일반기업회계기준", title: "온실가스 배출권과 배출부채" },
  // ---- 기타기준서(특수분야) ----
  { stdNum: 5001, category: "기타기준서", title: "결합재무제표" },
  { stdNum: 5002, category: "기타기준서", title: "기업구조조정투자회사" },
  { stdNum: 5003, category: "기타기준서", title: "집합투자기구" },
  { stdNum: 5004, category: "기타기준서", title: "신탁업자의 신탁계정" },
];
